FROM alpine:3.13

LABEL name="Base Alpine" \
vendor="Screaming Bunny" \
license="BSD" \
version="2.0" \
description="This is the Base Alpine container for Screaming Bunny."

COPY modules/tmp/ /tmp/

# Package installation
# Packages - https://pkgs.alpinelinux.org/packages
RUN apk upgrade --update && \
apk add --no-cache bash \
  curl \
  git \
  shadow \
  tar \
  dos2unix && \
#
# Dockerize Config
tar -C /usr/local/bin -xzvf /tmp/dockerize-alpine-linux-amd64-*.tar.gz && \
#
# Wait Config
mv /tmp/wait /usr/local/bin/wait && \
chmod +x /usr/local/bin/wait && \
#
# Cleanup
apk del --no-cache tar && \
rm -rf /var/cache/apk/* *.tar.gz* /usr/src /root/.cache /root/.gnupg /tmp/*
