# BASE_IMAGE - arg is the tag of the container built from Dockerfile_alpine-python3
ARG BASE_IMAGE
FROM $BASE_IMAGE

LABEL name="Actuator Alpine Python3" \
description="This is the Actuator Alpine Python3 with SB_Utils container for Screaming Bunny."

ADD modules/utils/actuator /tmp/sb_utils

# Package Installation
# Packages - https://pkgs.alpinelinux.org/packages
#
# SB_Utils install
RUN cd /tmp/sb_utils && \
python3 setup.py install && \
cd && \
#
# Cleanup
rm -rf /var/cache/apk/* *.tar.gz* /usr/src /root/.gnupg /tmp/* && \
#
# Check versions
python3 --version && \
pip3 --version