# BASE_IMAGE - arg is the tag of the container built from Dockerfile_alpine-python3
ARG BASE_IMAGE
FROM $BASE_IMAGE

LABEL name="Twisted Alpine Python3" \
description="This is the Twisted Alpine Python3 with SB_Utils container for Screaming Bunny."

ADD modules/utils/twisted /tmp/sb_utils

# Package Installation
# Packages - https://pkgs.alpinelinux.org/packages
RUN apk add --no-cache python3 && \
apk add --no-cache --virtual .build-deps \
  g++ \
  gcc \
  musl-dev \
  yaml-dev \
  python3-dev && \
#
# SB_Utils install
cd /tmp/sb_utils && \
python3 setup.py install && \
cd && \
#
# Cleanup
apk del .build-deps && \
rm -rf /var/cache/apk/* *.tar.gz* /usr/src /root/.gnupg /tmp/* && \
#
# Check versions
python3 --version && \
pip3 --version
