FROM oif/base:alpine-python3

MAINTAINER Screaming_Bunny

LABEL name="Base Alpine Python3" \
vendor="Screaming Bunny" \
license="BSD" \
version="2.0" \
description="This is the Base Alpine Python3 container for Screaming Bunny."

ADD modules/ /tmp/modules

# SB_Utils install
RUN cd /tmp/modules/utils && \
python3 setup.py install && \
cd && \
#
# Cleanup
rm -rf /var/cache/apk/* *.tar.gz* /usr/src /root/.gnupg /tmp/*
