FROM alpine:latest

LABEL name="Base Alpine" \
vendor="Screaming Bunny" \
license="BSD" \
version="2.0" \
description="This is the Base Alpine container for Screaming Bunny."

ENV DOCKERIZE_VERSION v0.6.1

COPY modules/tmp/ /tmp/

# Package installation
# Packages - https://pkgs.alpinelinux.org/packages
RUN apk upgrade --update && \
apk add --no-cache bash \
  curl \
  shadow \
  tar \
  dos2unix && \
#
# Dockerize Config
tar -C /usr/local/bin -xzvf /tmp/dockerize-alpine-linux-amd64-${DOCKERIZE_VERSION}.tar.gz && \
#
# Cleanup
apk del --no-cache tar && \
rm -rf /var/cache/apk/* *.tar.gz* /usr/src /root/.cache /root/.gnupg /tmp/*
