FROM alpine:latest

MAINTAINER Screaming_Bunny

LABEL name="Base Alpine Python3" \
vendor="Screaming Bunny" \
license="BSD" \
version="2.0" \
description="This is the Base Alpine Python3 container for Screaming Bunny."

ENV DOCKERIZE_VERSION=v0.6.1 \
    PYTHONUNBUFFERED=0

ADD modules/ /tmp/modules
ADD https://github.com/jwilder/dockerize/releases/download/${DOCKERIZE_VERSION}/dockerize-alpine-linux-amd64-${DOCKERIZE_VERSION}.tar.gz /tmp/dockerize.tar.gz
ADD https://bootstrap.pypa.io/get-pip.py /tmp/get-pip.py

# Package Installation
# Packages - https://pkgs.alpinelinux.org/packages
RUN apk upgrade --update && \
apk add --no-cache python3 \
  bash \
  shadow \
  tar \
  dos2unix && \
apk add --no-cache --virtual .build-deps \
  g++ \
  gcc \
  musl-dev \
  yaml-dev \
  python3-dev && \
#
# Dockerize Config
tar -C /usr/local/bin -xzvf /tmp/dockerize.tar.gz && \
#
# Python PIP Install
python3 /tmp/get-pip.py && \
pip3 install --upgrade pip && \
#
# SB_Utils install
cd /tmp/modules/utils/root && \
python3 setup.py install && \
cd /tmp/modules/utils/twisted && \
python3 setup.py install && \
cd && \
#
# Cleanup
apk del .build-deps tar && \
rm -rf /var/cache/apk/* *.tar.gz* /usr/src /root/.gnupg /tmp/* && \
#
# Check versions
python3 --version && \
pip3 --version
