ARG BASE_IMAGE=${BASE_IMAGE:-'alpine:latest'}
FROM $BASE_IMAGE

MAINTAINER Screaming_Bunny

LABEL name="Base Alpine Python3 Twisted" \
vendor="Screaming Bunny" \
license="BSD" \
version="2.0" \
description="This is the Base Alpine Python3 container for Screaming Bunny."

ENV DOCKERIZE_VERSION=${DOCKERIZE_VERSION:-v0.6.1} \
    PYTHONUNBUFFERED=${PYTHONUNBUFFERED:-0}

ADD basic_setup.sh /
ADD python_setup.sh /
ADD twisted_setup.sh /
ADD modules/utils /tmp/modules

# Check basic setup
RUN chmod +x /basic_setup.sh /python_setup.sh /twisted_setup.sh && \
if [ "$BASE_IMAGE" = "alpine:latest" ]; then /basic_setup.sh && /python_setup.sh; fi && \
/twisted_setup.sh
