# BASE_IMAGE - arg is the tag of the container built from Dockerfile_alpine
ARG BASE_IMAGE

# Builder
FROM $BASE_IMAGE as builder

ENV VPACK_VERSION=0.1.33

ADD modules/tmp/* /tmp/

RUN apk add --no-cache \
  cmake \
  g++ \
  gcc \
  make \
  unzip && \
#
# VelocityPack Install
unzip -q -d /tmp/ /tmp/velocypack-${VPACK_VERSION}.zip && \
cd /tmp/velocypack-${VPACK_VERSION} && \
mkdir -p ./build && \
(cd build && cmake .. && make install DESTDIR=/opt/velocitypack)


# Base Image
FROM $BASE_IMAGE

LABEL name="Base Alpine Python3" \
description="This is the Base Alpine Python3 with SB_Utils container for Screaming Bunny."

ENV PYTHONUNBUFFERED=0

COPY modules/tmp/ /tmp/
COPY --from=builder /opt/velocitypack /

# Package Installation
# Packages - https://pkgs.alpinelinux.org/packages
RUN apk add --no-cache libressl libstdc++ python3 && \
apk add --no-cache --virtual .build-deps \
  cargo \
  gcc \
  g++ \
  libffi-dev \
  libressl-dev \
  linux-headers \
  musl-dev \
  openssl-dev \
  python3-dev \
  yaml-dev && \
#
# Python PIP Install
python3 /tmp/get-pip.py && \
pip3 install --no-cache-dir --upgrade pip setuptools && \
#
# SB_Utils install
cd /tmp/sb_utils/root && \
pip3 install --no-cache-dir . && \
cd && \
#
# Cleanup
apk del --no-cache .build-deps && \
rm -rf /var/cache/apk/* *.tar.gz* /usr/src /root/.cache /root/.gnupg /tmp/* && \
#
# Check versions
python3 --version && \
pip3 --version && \
json-to-vpack --help && \
vpack-to-json --help
